AppBundle\Entity\Entreprises:
    type: entity
    table: entreprises
    indexes:
        pays:
            columns:
                - id_pays
    id:
        idEntreprise:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: id_entreprise
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        commentaires:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    manyToOne:
        idPays:
            targetEntity: Pays
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_pays:
                    referencedColumnName: id_pays
            orphanRemoval: false
    lifecycleCallbacks: {  }
