AppBundle\Entity\IndicePdf:
    type: entity
    table: indice_pdf
    indexes:
        idx_nom:
            columns:
                - nom_pdf
    id:
        idIndicePdf:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: id_indice_pdf
            generator:
                strategy: IDENTITY
    fields:
        datePdf:
            type: date
            nullable: false
            column: date_pdf
        nomPdf:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                default: ''
            column: nom_pdf
    lifecycleCallbacks: {  }
