AppBundle\Entity\IndiceBoursier:
    type: entity
    table: indice_boursier
    indexes:
        idx_nom:
            columns:
                - Nom
    id:
        idIndiceBoursier:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: id_indice_boursier
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: Nom
        nomEn:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: Nom_en
    lifecycleCallbacks: {  }
