AppBundle\Entity\MailTemplates:
    type: entity
    table: mail_templates
    indexes:
        idx_titre:
            columns:
                - titre
    id:
        idMailTemplates:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: id_mail_templates
            generator:
                strategy: IDENTITY
    fields:
        titre:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        contenu:
            type: blob
            nullable: true
            length: 65535
            options:
                fixed: false
    lifecycleCallbacks: {  }
