AppBundle\Entity\Pages:
    type: entity
    table: pages
    indexes:
        idx_titre:
            columns:
                - titre
    id:
        idPage:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: id_page
            generator:
                strategy: IDENTITY
    fields:
        titre:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
