AppBundle\Entity\Pays:
    type: entity
    table: pays
    indexes:
        idx_nom:
            columns:
                - nom_pays
    id:
        idPays:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: id_pays
            generator:
                strategy: IDENTITY
    fields:
        nomPays:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: nom_pays
        nomPaysEn:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: nom_pays_en
    lifecycleCallbacks: {  }
