AppBundle\Entity\Referentiel:
    type: entity
    table: referentiel
    indexes:
        index2:
            columns:
                - defaut
        index5:
            columns:
                - libelle_en
    uniqueConstraints:
        code_UNIQUE:
            columns:
                - code
    id:
        idReferentiel:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: id_referentiel
        libelle:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            id: true
    fields:
        libelleEn:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: libelle_en
        defaut:
            type: boolean
            nullable: true
        code:
            type: string
            nullable: true
            length: 16
            options:
                fixed: false
    lifecycleCallbacks: {  }
