AppBundle\Entity\ReferentielFamille:
    type: entity
    table: referentiel_famille
    indexes:
        fk_referentiel_famille_famille1_idx:
            columns:
                - id_famille
        fk_referentiel_famille_referentiel1_idx:
            columns:
                - id_referentiel
    id:
        ordre:
            type: integer
            nullable: true
            options:
                unsigned: true
            id: true
        idFamille:
            associationKey: true
        idReferentiel:
            associationKey: true
    oneToOne:
        idFamille:
            targetEntity: Famille
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_famille:
                    referencedColumnName: id_famille
            orphanRemoval: false
        idReferentiel:
            targetEntity: Referentiel
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_referentiel:
                    referencedColumnName: id_referentiel
            orphanRemoval: false
    lifecycleCallbacks: {  }
