AppBundle\Entity\SousFamille:
    type: entity
    table: sous_famille
    uniqueConstraints:
        code_UNIQUE:
            columns:
                - code
    id:
        idSousFamille:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: id_sous_famille
            generator:
                strategy: IDENTITY
    fields:
        libelle:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        libelleEn:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: libelle_en
        code:
            type: string
            nullable: true
            length: 16
            options:
                fixed: false
    lifecycleCallbacks: {  }
