AppBundle\Entity\TypeModeleAffichage:
    type: entity
    table: type_modele_affichage
    id:
        idTypeModeleAffichage:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: id_type_modele_affichage
            generator:
                strategy: IDENTITY
    fields:
        label:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
